config/routes.rb
Rails.application.routes.draw do
  resources :videos
  get 'pages/about'

  get 'pages/contact'

end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :google_key

  def google_key
    return ENV["GOOGLE_MAPS_API_KEY"]
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        # send email
        VideoMailerWorker.perform_async(@video.title)

        # redirect
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:wistia, :description, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Code4newbies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{google_key}" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= yield(:head_tags) %> 
</head>
<body>
  <nav>
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo">Code4Newbies</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#"><i class="material-icons">branding_watermark</i></a></li>
        <li><a href="#"><i class="material-icons">loyalty</i></a></li>
        <li><a href="#"><i class="material-icons">map</i></a></li>
      </ul>
    </div>
  </nav>

  <ul class="sidenav" id="mobile-demo">
    <li><a href="#"><i class="material-icons">branding_watermark</i></a></li>
        <li><a href="#"><i class="material-icons">loyalty</i></a></li>
        <li><a href="#"><i class="material-icons">map</i></a></li>
  </ul>

  <div class="row">
    <div clas="col m10 offset-m1">
      <%= yield %>
    </div>
  </div>

 

  <script>
    $('.sidenav').sidenav();
  </script>
  
</body>
</html>

app/views/pages/about.html.erb
<h3>About me</h3>

<div class="cardz-depth-3">
    <div class="card-content white-text">
        <div class="col m6">
            <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-size="large" data-text="sssdd" data-via="d" data-hashtags="dddd" data-related="ddedfcw,efcwerfcwfcefwe" data-dnt="true" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
        <div class="col m6">
            <div class="card-panel grey lighten-5 z-depth-1">
                <div class="row valign-wrapper">
                    <div class="col m3">
                        <%= image_tag "avatar.jpg", class: "circle responsive-img"%>
                    </div>
                    <div class="col m9">
                        <span class="black-text">"I dont know what to say"</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/contact.html.erb
<h3>Contact</h3>

<div id="map"></div>

<div class="card z-depth-3">
    <div class="card-content">
        <p id="text">Do you wanna contact</p>
    </div>
</div>

<% provide :head_tags do %>
    <script>
        document.addEventListener("DOMContentLoaded", function(){
            initMap()
        });
    </script>
<% end %>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= f.text_field :wistia, :placeholder => 'Link', :length => '10' %>
  </div>
  <div class="input-field">
    <%= f.text_field :title, :placeholder => 'Title', :length => '20' %>
  </div>
  <div class="input-field">
    <%= f.text_area :description, :placeholder => 'Description', :length => '800', :class => 'materialize-textarea' %>
  </div>
  <button class="btn waves-effect waves-light" type="submit" name="action">Submit</button>
  <a href="<%= videos_path %>" class="btn waves-effect waves-light" name="action">Back</a>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<div class="card">
    <div class="card-content">
        <%= render 'form'%>
    </div>
</div>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Videos</h1>

<table>
  <thead>
    <tr>
      <th>Wistia</th>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.wistia %></td>
        <td><%= video.title %></td>
        <td><%= video.description %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<div class="card">
    <div class="card-content">
        <%= render 'form'%>
    </div>
</div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<script src="//fast.wistia.com/embed/medias/j38ihh83m5.jsonp" async></script>
<script src="//fast.wistia.com/assets/external/E-v1.js" async></script>

<div class="row">
  <div class="col m3">
    <div class="collection">
      <ul class="collection">
        
<div class="wistia_embed wistia_async_j38ihh83m5" style="height:349px;width:620px">&nbsp;</div>
      </ul>
    </div>
  </div>
  <div class="col m9">

  </div>
</div>